const GENERATE_DATA_KEY_ERRORS = {
  errorCode: 'AwsKms::GENERATE_DATA_KEY_ERRORS'
}

const GENERATE_DATA_KEY_PAIR_ERRORS = {
  errorCode: 'AwsKms::GENERATE_DATA_KEY_PAIR_ERRORS'
}

const ENCRYPT_ERRORS = {
  errorCode: 'AwsKms::ENCRYPT_ERRORS'
}

const DECRYPT_ERRORS = {
  errorCode: 'AwsKms::DECRYPT_ERRORS'
}

export {
  GENERATE_DATA_KEY_ERRORS,
  GENERATE_DATA_KEY_PAIR_ERRORS,
  ENCRYPT_ERRORS,
  DECRYPT_ERRORS
}
