const {
  // API_CRYPTO_KMS_ENABLED = '',
  KMS_TYPE = 'NODE',
  KMS_KEY_PAIR_ALGO = 'rsa',
  KMS_KEY_PAIR_LENGTH = '2048',
  KMS_KEY_ALGO = 'aes',
  KMS_KEY_LENGTH = '256',
  KMS_KEY_FORMAT = 'base64',
  KMS_PLAIN_TEXT_FORMAT = 'utf8',
  KMS_CIPHER_TEXT_FORMAT = 'base64',

  KMS_NODE_MASTER_KEY = '',
  KMS_NODE_MASTER_IV_HEX = '00000000000000000000000000000000',
  KMS_AWS_KEY_ID = ''
} = process.env

const REQUIRED_CONFIG = []

if (KMS_TYPE === 'NODE') {
  REQUIRED_CONFIG.push('KMS_NODE_MASTER_KEY')
}

if (KMS_TYPE === 'AWS') {
  REQUIRED_CONFIG.push('KMS_AWS_KEY_ID')
}

REQUIRED_CONFIG.forEach(function (key) {
  if (!process.env[key]) {
    console.error('[Error] Kms Config Missing:', key)
    return process.exit(1)
  }
})

const CONFIG = {
  TYPE: KMS_TYPE,
  KEY_PAIR_ALGO: KMS_KEY_PAIR_ALGO,
  KEY_PAIR_LENGTH: KMS_KEY_PAIR_LENGTH,
  KEY_ALGO: KMS_KEY_ALGO,
  KEY_LENGTH: KMS_KEY_LENGTH,
  KEY_FORMAT: KMS_KEY_FORMAT,
  PLAIN_TEXT_FORMAT: KMS_PLAIN_TEXT_FORMAT,
  CIPHER_TEXT_FORMAT: KMS_CIPHER_TEXT_FORMAT,

  NODE_MASTER_KEY: KMS_NODE_MASTER_KEY,
  NODE_MASTER_IV_HEX: KMS_NODE_MASTER_IV_HEX,
  AWS_KEY_ID: KMS_AWS_KEY_ID
}

export default CONFIG
